Feature/user repository class
kpn678/fitlit pull request #8
Opened 2022-05-15 21:46 UTC by GrantXBeard

Hello, team! Please review this PR!

What does this PR do?
-added userRepository class and testing file.

Where should your reviewer start?
- Line number one on both files.

What (if any) features are you implementing?
- userRepository class and tests.

Does this PR close any open issues?
- Closes #7 

Thank you!!

2022-05-15 21:59 UTC, jordan-sullivan requested changes
Looks great team! Remove comments and good to go! -J

2022-05-15 22:01 UTC, kpn678 commented on test/UserRepository-test.js
> +  // console.log("1", userData);
Please remove console.log()

2022-05-15 22:02 UTC, kpn678 reviewed
Looks good, please remove line 6 on UserRepository-test.

2022-05-15 23:42 UTC, GrantXBeard commented on test/UserRepository-test.js
> +  // console.log("1", userData);
console log removed.

2022-05-16 19:00 UTC, kpn678 reviewed
Excellent, the changes look good to me! I think it is ready to be merged if Jordan thinks so, too.

2022-05-16 19:35 UTC, merged